<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class Rekam_medis_model extends CI_Model
{

    public $table = 'rekam_medis';
    public $id 	  = 'id_rekam_medis';
    public $order = 'DESC';

    function __construct(){
        parent::__construct();
    }
	
    function tampil_pasien(){
        $this->db->select('rekam_medis.id_rekam_medis');
        $this->db->select('booking.id_booking');
        $this->db->select('rekam_medis.keluhan_utama');
        $this->db->select('booking.nama');
        
        $this->db->join('antrian','rekam_medis.id_rekam_medis=antrian.id_rekam_medis');
        $this->db->join('booking','antrian.id_booking=booking.id_booking');
        echo json_encode($this->db->get($this->table)->result());
    }
    
	public function get_pasien()
    {
        $query = $this->db->select("*")
                 ->from('rekam_medis')
                 ->order_by('id_rekam_medis', 'ASC')
                 ->where('id_user', $this->session->userdata('id_user'))
                 ->get();
        return $query->result();
    }

    // get all
    function get_all(){
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id){
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function get_id_last() {
        $this->db->select($this->id);
        $this->db->order_by($this->id,$this->order);
        $this->db->limit(1,0);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
		$this->db->or_like('tanggal', $q);
		$this->db->or_like('nama_pasien', $q);
		$this->db->or_like('diagnosis', $q);
		$this->db->or_like('tanggal_next_control', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
		$this->db->or_like('tanggal', $q);
		$this->db->or_like('nama_pasien', $q);
		$this->db->or_like('diagnosis', $q);
		$this->db->or_like('tanggal_next_control', $q);
		$this->db->limit($limit, $start);
		$this->db->join('booking',$this->table.'.id_booking=booking.id_booking');
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data,$id){
        $this->db->insert($this->table, $data);        
    }

   

    // update data
    function update($id, $data){
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id){
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}
/* End of file Rekam_medis_model.php */
/* Location: ./application/models/Rekam_medis_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-07-29 06:09:49 */
/* http://harviacode.com */